---
- name: create symlinks for files at .sync folder
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    src: "{{ home_path }}/.sync/{{ item }}"
    dest: "{{ home_path }}/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - Documents
    - Downloads
    - ProgramasRFB
    - Projects
    - .aws
    - .config/gh
    - .gnupg/pubring.kbx
    - .gnupg/tofu.db
    - .gnupg/trustdb.gpg
    - .local/share/backgrounds
    - .local/share/keyrings
    - .password-store
    - .ssh
    - .kube
