---
- name: get the disk ID
  become: true
  shell: lsblk --fs | grep {{ windows_boot_partition.unix_name }} | grep -Eo '[A-F0-9]{16}'
  register: windows_partition

- set_fact: partition_id={{ windows_partition.stdout }}

- name: add Windows bootloader entry
  become: true
  notify: rebuild grub
  template: src=templates/windows_bios_entry.j2 dest=/etc/grub.d/40_windows mode=0755
