---
- name: remove extra booting options
  become: true
  notify: rebuild grub
  copy: src=files/10_linux dest=/etc/grub.d/10_linux mode=0755

- name: change default timeout to 3 seconds
  become: true
  notify: rebuild grub
  lineinfile: path=/etc/default/grub regexp="^GRUB_TIMEOUT=" line="GRUB_TIMEOUT=3"
