[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 0

[mouse]
# Hides the cursor temporarily when typing.
hide_when_typing = true

[terminal.shell]
# The -A flag makes new-session behave like attach-session if session-name already exists
args = ["tmux", "new-session", "-A"]
program = "/usr/bin/env"

[env]
# Enable true-color support
LANG = "en_US.UTF-8"
TERM = "tmux-256color"

# Send \x1c (C-\) and the "key" that you want to send to Tmux. For instance, if I want to map
# CMD-D to tmux, then use it as the following:
# `- { key: D, mods: Command, chars: "\x1cd" }`
# And then "capture it" on tmux keybindings as if they are using a C-\ prefix (by using a custom
# key table):
# `bind -T alacritty d split-window -h`

# Apparently, C-6 and C-/ don't work by default on Alacritty/Mac
[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[general]
# Live config reload (changes require restart)
live_config_reload = true
