[window]
startup_mode = "Maximized"
title = "Terminal"

[window.padding]
x = 4

[cursor]
# Cursor blinking interval in milliseconds.
blink_interval = 400

[cursor.style]
# Cursor blinking state
#
# Values for `blinking`:
#   - Never: Prevent the cursor from ever blinking
#   - Off: Disable blinking by default
#   - On: Enable blinking by default
#   - Always: Force the cursor to always blink
blinking = "Always"

[general]
import = ["~/.config/alacritty/themes/one-light.toml"]
