modules = [
  "fish",
  "shell",
  "meta",
  "projects",
  "gnupg",
  "nvim",

  # Dev-related
  "ai",
  "git",
  "devops",
  "tmux",
  "asdf",
  "python",
  "javascript",
  { name = "ruby", scopes = ["personal", "devbox"] },
  { name = "golang", scopes = ["personal", "devbox"] },
  { name = "git-ssh-sign", scopes = ["devbox"] },

  # Only for UI
  { name = "ghostty", scopes = ["personal", "work"] },
  { name = "yazi", scopes = ["personal", "work"] },

  # Only for Linux
  { name = "linux", scopes = "personal" },

  # Only for my Home desktop
  { name = "borgmatic", scopes = "personal" },
  { name = "psi-notify", scopes = "personal" },
  { name = "fontconfig", scopes = "personal" },
  { name = "kde", scopes = "personal" },
  { name = "zathura", scopes = "personal" },
  { name = "vlc", scopes = "personal" },

  # Only for Work
  { name = "macos", scopes = "work" },
  { name = "work", scopes = "work" },
  { name = "ghostty-mac", scopes = "work" },

  # Disabled
  # { name = "gnome", scopes = "desktop" },
  # { name = "emacs" },
]
