---
- name: set default user settings
  become: true
  ansible.builtin.copy:
    src: gnome-user-settings
    dest: /var/lib/AccountsService/users/{{ user_name }}
    mode: "0644"

- name: import gnome settings
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command:
    cmd: dbus-launch dconf load /
    stdin: "{{ lookup('ansible.builtin.template', 'files/settings.dconf.j2') }}"

- name: create automatic dconf systemd service
  become: true
  become_user: "{{ user_name }}"
  register: dconf_auto_dumper
  ansible.builtin.copy:
    dest: "{{ home_path }}/.config/systemd/user/gnome-auto-dconf-dump.{{ item }}"
    src: "gnome-auto-dconf-dump.{{ item }}"
  loop:
    - service
    - timer

- name: enable and start automatic dconf systemd service
  become: true
  become_user: "{{ user_name }}"
  when: dconf_auto_dumper.changed
  ansible.builtin.systemd:
    name: gnome-auto-dconf-dump.timer
    daemon_reload: yes
    scope: user
    enabled: yes

- name: synchronize user password changes for gnome-keyring (bugfix)
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/passwd
    line: password	optional	pam_gnome_keyring.so
