---
  # Disable Wayland on proprietary Nvidia drivers
  # See: https://bugs.archlinux.org/task/53284
- name: disable Wayland on GDM
  become: true
  ansible.builtin.lineinfile:
    path: /etc/gdm/custom.conf
    line: "WaylandEnable=false"
    regexp: "#?WaylandEnable=false"

- name: scale gnome to hidpi monitor
  become: true
  become_user: "{{ item }}"
  ansible.builtin.command: dbus-launch gsettings set org.gnome.desktop.interface scaling-factor 2
  when: use_hidpi == true
  loop:
    - "{{ user_name }}"
    - gdm

- name: scale fonts out when not using hidpi
  become: true
  become_user: "{{ item }}"
  ansible.builtin.command: dbus-launch gsettings set org.gnome.desktop.interface text-scaling-factor 1.10
  when: use_hidpi == false
  loop:
    - "{{ user_name }}"
    - gdm

- name: set default user settings
  become: true
  ansible.builtin.copy:
    src: gnome-user-settings
    dest: /var/lib/AccountsService/users/{{ user_name }}
    mode: "0644"

- name: synchronize user password changes for gnome-keyring
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/passwd
    line: password	optional	pam_gnome_keyring.so
