---
# If GDM ever gets troublesome when using Wayland, it's better to disable it
# from loading from Wayland and use Xorg instead
# This is an issue with NVIDIA
# See: https://bugs.archlinux.org/task/53284
- name: disable Wayland on GDM
  become: true
  when: "'nvidia' in role_names"
  lineinfile:
    path: /etc/gdm/custom.conf
    line: "WaylandEnable=false"
    regexp: "#?WaylandEnable=false"
