---
- name: install gnome
  become: true
  pacman: 
    state: present
    name:
      - xorg
      - gnome-shell
      - gdm

      # Base GNOME apps
      - networkmanager
      - nautilus
      - gnome-control-center
      - gnome-backgrounds
      - gnome-screenshot
      - gnome-calculator
      - gnome-system-monitor
      - gnome-font-viewer
      - gnome-disk-utility
      - gnome-tweaks
      - gnome-keyring
      - seahorse
      - evince
      - gedit
      - gthumb

      # Shell extensions
      - gnome-shell-extensions

      # Enable MTP protocol (for connecting phones)
      - gvfs-mtp

- name: install AUR packages for customized gnome
  become: true
  become_user: "{{ user_name }}"
  command: bin/pkg build --install {{ item }}
  args:
    chdir: /home/{{ user_name }}/Projects/PKGBUILDs
  loop:
    - stil-gnome-theme-git
    - gnome-shell-extension-system-monitor-git
    - gnome-shell-extension-remove-accessibility

- name: enable gdm and networkmanager at boot time
  become: true
  systemd: name={{ item }} enabled=true
  loop:
    - NetworkManager.service
    - gdm.service
