---
- name: install gnome
  become: true
  community.general.pacman:
    state: present
    name:
      - gnome-shell
      - gdm

      # Base GNOME apps
      - nautilus
      - gnome-control-center
      - gnome-backgrounds
      - gnome-system-monitor
      - gnome-font-viewer
      - gnome-disk-utility
      - gnome-tweaks
      - gnome-keyring
      - seahorse

      # Shell extensions
      - gnome-shell-extensions

      # Enable MTP protocol (for connecting phones)
      - gvfs-mtp

      # Enable NFS & SMB on Nautilus
      - gvfs-nfs
      - gvfs-smb

      # pinentry-gnome3 dependency
      - gcr

- name: install gnome extensions from AUR
  become: true
  become_user: "{{ user_name }}"
  aur:
    name:
      - gnome-shell-extension-system-monitor-next-git
      - gnome-shell-extension-impatience-git

- name: enable gdm at boot time
  become: true
  ansible.builtin.systemd: name=gdm enabled=true
