---
- name: install gnome
  become: true
  community.general.pacman:
    state: present
    name:
      - xorg
      - gnome-shell
      - gdm

      # Base GNOME apps
      - networkmanager
      - nautilus
      - gnome-control-center
      - gnome-backgrounds
      - gnome-screenshot
      - gnome-calculator
      - gnome-system-monitor
      - gnome-font-viewer
      - gnome-disk-utility
      - gnome-tweaks
      - gnome-keyring
      - seahorse
      - evince
      - gedit

      # Image view
      - nomacs

      # Shell extensions
      - gnome-shell-extensions

      # Enable MTP protocol (for connecting phones)
      - gvfs-mtp

      # Enable NFS & SMB on Nautilus
      - gvfs-nfs
      - gvfs-smb

      # pinentry-gnome3 dependency
      - gcr

      # ---------------------
      # Packages on AUR/pacom
      - gnome-shell-extension-system-monitor-git
      - gnome-shell-extension-impatience

- name: enable gdm at boot time
  become: true
  ansible.builtin.systemd: name=gdm enabled=true
