---
- name: install gnome
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - xorg
    - gnome-shell
    - gnome-control-center
    - gnome-backgrounds
    - gnome-calculator
    - gnome-system-monitor
    - gdm
    # Eye of gnome is a image viewer
    - eog
    # PDF Viewer
    - evince
    # Font viewer
    - gnome-font-viewer
    # This is a tool to customize gnome
    - gnome-tweaks

    # System monitor plugin (available on kriansa-aur)
    - gnome-shell-extension-system-monitor-git

    # Xclip allows interaction with clipboard
    - xclip
    # This is required to enable numlock on xorg
    - numlockx
    # We can use any network manager, but GNOME's NetworkManager works
    # seamlessly across the environment.
    # see: https://wiki.archlinux.org/index.php/List_of_applications/Internet#Network_managers
    - networkmanager
    # xinit is only needed when we aren't going to use GDM. In which case, we
    # can start xorg manually by running `startx`
    #
    # If you ever want to do so, please beware to execute .xprofile on you
    # .xinit
    #
    # see: https://wiki.archlinux.org/index.php/Xinit
    # - xorg-xinit

- name: enable gdm and networkmanager at boot time
  become: true
  systemd: name={{ item }} enabled=true
  with_items:
    - NetworkManager.service
    - gdm.service

- name: scale gnome to hidpi monitor
  become: true
  become_user: "{{ item }}"
  command: dbus-launch gsettings set org.gnome.desktop.interface scaling-factor 2
  when: use_hidpi == true
  with_items:
    - "{{ user_name }}"
    - gdm

- name: set user avatar
  become: true
  copy:
    src: files/gnome-user-settings
    dest: /var/lib/AccountsService/users/{{ user_name }}
    mode: 0644

- name: setup gnome
  become: true
  become_user: "{{ user_name }}"
  command: dbus-launch gsettings set {{ item.path }} {{ item.name }} "{{ item.value }}"
  with_items:
    - { path: org.gnome.desktop.interface, name: clock-show-date, value: "true" }
    - { path: org.gnome.desktop.privacy, name: remember-recent-files, value: "false" }
    # Configure BR keyboard
    - { path: org.gnome.desktop.input-sources, name: sources, value: "[('xkb', 'br')]" }
    # Disable auto-suspend
    - { path: org.gnome.settings-daemon.plugins.power, name: sleep-inactive-ac-type, value: "nothing" }
    # Disable media auto-run
    - { path: org.gnome.desktop.media-handling, name: autorun-never, value: "true" }
    # Theme
    - { path: org.gnome.desktop.interface, name: gtk-theme, value: "Adwaita" }
    # Fonts
    - { path: org.gnome.desktop.interface, name: monospace-font-name, value: "Roboto Mono 11" }
    - { path: org.gnome.desktop.interface, name: font-name, value: "Roboto Condensed, 11" }
    - { path: org.gnome.desktop.interface, name: document-font-name, value: "Roboto Medium 11" }
    - { path: org.gnome.desktop.wm.preferences, name: titlebar-uses-system-font, value: "true" }
    - { path: org.gnome.desktop.wm.preferences, name: titlebar-font, value: "Roboto Condensed, Bold 11" }
    # Menu bar
    - { path: org.gnome.desktop.wm.preferences, name: button-layout, value: "appmenu:minimize,maximize,close" }
    # Nautilus
    - { path: org.gnome.nautilus.icon-view, name: default-zoom-level, value: "small" }
    - { path: org.gnome.nautilus.window-state, name: maximized, value: "true" }
    - { path: org.gnome.nautilus.preferences, name: show-hidden-files, value: "true" }
    - { path: org.gtk.Settings.FileChooser, name: show-hidden, value: "true" }
    # FileChooser sorting
    - { path: org.gtk.Settings.FileChooser, name: sort-directories-first, value: "true" }
    - { path: org.gtk.Settings.FileChooser, name: sort-order, value: "ascending" }
    - { path: org.gtk.Settings.FileChooser, name: sort-column, value: "name" }
    # Backgrounds
    - { path: org.gnome.desktop.background, name: picture-uri, value: "file:///usr/share/backgrounds/gnome/adwaita-timed.xml" }
    - { path: org.gnome.desktop.screensaver, name: picture-uri, value: "file:///usr/share/backgrounds/gnome/adwaita-timed.xml" }
    # Set keyboard rate & delay
    - { path: org.gnome.desktop.peripherals.keyboard, name: repeat-interval, value: "uint32 30" }
    - { path: org.gnome.desktop.peripherals.keyboard, name: delay, value: "uint32 250" }
    # Set the shortcuts on the sidebar (favorites)
    - path: org.gnome.shell
      name: favorite-apps
      value: ['org.gnome.Nautilus.desktop', 'com.gexperts.Tilix.desktop', 'firefox.desktop', 'spotify.desktop']
    # Enable & configure system-monitor shell extension
    - { path: org.gnome.shell, name: enabled-extensions, value: "['system-monitor@paradoxxx.zero.gmail.com']" }
    - { path: org.gnome.shell.extensions.system-monitor, name: icon-display, value: "false" }
    - { path: org.gnome.shell.extensions.system-monitor, name: gpu-show-menu, value: "true" }
    - { path: org.gnome.shell.extensions.system-monitor, name: disk-usage-style, value: "'none'" }
