---
# Hostname of this machine
hostname: daniel-desktop.lan.cx

# The username we want to create
user_name: dpereira
home_path: /home/{{ user_name }}

# This user comment appears on Gnome-shell
user_comment: Daniel Pereira

# Base locale settings
arch_locale: en_US.UTF-8
arch_keymap: us
arch_timezone: America/Sao_Paulo

# For all machine-dependent config files, append this suffix to determine which one to use
config_file_suffix: desktop

# Nvidia settings
# This has proven to reduce boot failures on Desktop VGAs (such as RTX 2060S)
disable_nvidia_i2c: true

# Intel drivers
install_intel_drivers: false

# Install nvidia
install_nvidia_drivers: false
# See: https://www.x.org/releases/X11R7.7/doc/man/man5/xorg.conf.5.xhtml
# Get this info by running lspci
nvidia_bus_id: PCI:1:0:0

# Install amd
install_amd_drivers: true

# Enable bluetooth?
enable_bluetooth: false
