---
- name: create .config/fontconfig directory
  become: true
  become_user: "{{ user_name }}"
  file: path="{{ home_path }}/.config/fontconfig/conf.d" state=directory mode=0755

- import_tasks: link_files.yml
  vars:
    plugin_name: fontconfig
    files:
      - .config/fontconfig/fonts.conf
      - .config/fontconfig/conf.d/aliases.conf
      - .config/fontconfig/conf.d/emoji.conf
