---
# TODO: Arch Linux only. Adapt to work on MacOS.

- name: generate .gitconfig file
  become: true
  become_user: "{{ user_name }}"
  template: 
    src: templates/.gitconfig.j2 
    dest: "{{ dotfiles_path }}/plugins/git/include/.gitconfig" 
    mode: 0644

- include_tasks: link_files.yml
  vars:
    plugin_name: git
    files:
      - .gitconfig
      - .gitmessage
