---
# TODO: Arch Linux only. Adapt to work on MacOS.

- name: install development packages
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - python
    - python-pip
    - tmux
    - gcr # pinentry-gnome3 dependency
    - atom
    - cowsay
    - neovim
    - ncdu
    - jq
    - the_silver_searcher
    - aws-cli
    - shellcheck
    - tilix

    # DB
    - sqlitebrowser

    # Java stuff
    - jdk10-openjdk
    - gradle

    # Virtualization stuff
    - qemu
    - virt-manager
    - ebtables
    - dnsmasq

    # DevOps tools
    - terraform

    # LastPass CLI (lpass)
    - lastpass-cli

- name: install urxvt
  become: true
  become_user: "{{ user_name }}"
  command: pikaur -Syu --noconfirm --needed {{ item }}
  with_items:
    - rxvt-unicode-cvs-patched-wideglyphs
    - urxvt-resize-font-git

- name: install java
  become: true
  become_user: "{{ user_name }}"
  command: pikaur -Syu --noconfirm --needed jdk
  when: use_oracle_java == true

- name: set default java installation
  become: true
  shell: archlinux-java set "$(archlinux-java status | tail -2 | head -1 | cut -b 3-)"
  when: use_oracle_java == true
