---
- import_tasks: link_files.yml
  vars:
    plugin_name: tilix
    files:
      - .config/tilix

- name: import tilix settings
  become: true
  become_user: "{{ user_name }}"
  shell: dbus-launch dconf load /com/gexperts/Tilix/ < "{{ dotfiles_path }}/plugins/tilix/data/tilix.dconf"
