---
# The user we're installing to
# Should be the same set at base-arch's role
user_name: dpereira

# Set common paths
home_path: /home/{{ user_name }}

# Node & Ruby versions
node_version: 10.15.3
ruby_version: 2.6.3
