#!/usr/bin/env zsh

# Plugin <plugin name>
# Installation proccess:
#
#  1. Install needed packages
#  2. Adds symlinks
#  3. Etc task
#

source 'helpers/installer_helper.zsh'
PLUGIN_PATH=$0:A:h
DOTFILES_ROOT=$(pwd)

# 1. Install packages
if [[ OS_NAME == "OSX" ]]; then
  brew install etcpackage
fi

# 2. Adds symlinks into $HOME
link_file "$PLUGIN_PATH/inc/.keep" "$HOME/.git/.file"

if [[ OS_NAME == "OSX" ]]; then
  link_file "$PLUGIN_PATH/inc/launch-agent.plist"
fi

# 3. Etc task
echo $PLUGIN_PATH
