---
- name: check for presence of syncthing config
  become: true
  become_user: "{{ user_name }}"
  register: syncthing_config
  ansible.builtin.stat:
    path: "{{ home_path }}/.config/syncthing/config.xml"

- name: copy basic file structure from NFS directly
  when: not syncthing_config.stat.exists
  become: true
  block:
    - name: mount nfs path
      ansible.posix.mount:
        src: nas.lan.cx:/mnt/pool1/Systems/Syncthing/Daniel/Home
        path: /mnt/syncthing-home
        fstype: nfs
        state: mounted

    - name: create paths at home
      become_user: "{{ user_name }}"
      ansible.builtin.file:
        state: directory
        mode: "{{ item.mode }}"
        dest: "{{ home_path }}/{{ item.path }}"
      loop:
        - { path: .sync, mode: "0755" }
        - { path: .sync/.config, mode: "0755" }
        - { path: .sync/.config/syncthing, mode: "0700" }
        - { path: .config, mode: "0755" }
        - { path: .config/syncthing, mode: "0755" }
        - { path: .gnupg, mode: "0700" }
        - { path: .local, mode: "0700" }
        - { path: .local/share, mode: "0700" }
        - { path: .ssh, mode: "0700" }
        - { path: .aws, mode: "0755" }
        - { path: .password-store, mode: "0700" }

    - name: copy essential file structure from NFS directly
      become_user: "{{ user_name }}"
      ansible.builtin.copy:
        src: "/mnt/syncthing-home/{{ item }}/"
        dest: "{{ home_path }}/.sync/{{ item }}/"
        remote_src: yes
        mode: preserve
      loop:
        - .password-store
        - .config/syncthing
        - .ssh
        - .gnupg

    - name: unmount nfs path
      ansible.posix.mount:
        path: /mnt/syncthing-home
        state: absent

    - name: link syncthing config file
      become: true
      ansible.builtin.file:
        src: "{{ home_path }}/.sync/.config/syncthing/config-{{ config_file_suffix }}.xml"
        dest: "{{ home_path }}/.config/syncthing/config.xml"
        state: link

- name: create symlinks for files at .sync folder
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    src: "{{ home_path }}/.sync/{{ item }}"
    dest: "{{ home_path }}/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - Documents
    - Downloads
    - ProgramasRFB
    - Projects
    - .aws
    - .config/gh
    - .gnupg/pubring.kbx
    - .gnupg/tofu.db
    - .gnupg/trustdb.gpg
    - .local/share/backgrounds
    - .local/share/keyrings
    - .password-store
    - .ssh

- name: enable/start syncthing
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.systemd: name=syncthing enabled=yes state=started scope=user
