---
- name: install packages
  become: true
  notify: enable pcscd
  community.general.pacman:
    name:
      - pass
      - syncthing
      - gnupg
      - ccid
      - yubikey-manager
      - pam-u2f

# Make sure we restart pcscd at this point
- meta: flush_handlers
