---
# Install and configure password-store, GnuPG, Syncthing and ssh
- import_tasks: install_packages.yml
- import_tasks: setup_password_store.yml
- import_tasks: setup_gpg.yml
- import_tasks: configure_u2f_login.yml

# TODO: Setup Syncthing, then make both `~/.gnupg` and `~/.ssh` shared folders
