---
- name: check if password-store is present
  ansible.builtin.stat:
    path: "{{ home_path }}/.password-store"
  register: password_store_path

- name: clone password-store repository
  when: password_store_path.stat.isdir is not defined
  block:
    - name: run manual script locally
      become: true
      when: ansible_connection == "local"
      ansible.builtin.pause:
        echo: no
        prompt: |
          =================================================================
          Please, execute the following script interactively on your shell.
          {{ role_path }}/scripts/fetch-password-store
          Press Ctrl-C, then 'C' to continue or 'A' to abort.
          =================================================================

    - name: pull password manager secrets
      when: ansible_connection == "ssh"
      block:
        - name: pull password manager secrets
          ansible.builtin.git:
            repo: git@git.lan.cx:.password-store.git
            dest: "{{ home_path }}/.password-store"
            accept_hostkey: yes

          # This is necessary because when doing SSH Agent Forward, only the connecting user gets to use the
          # forwarded agent, and any `sudo` that we might need to do will not work for that forwarded
          # session due to invalid permissions. In that case, we simply do a git clone with the current
          # connecting user, which might be root OR my user, then we fix the permissions later, when needed.
          # See: https://unix.stackexchange.com/q/131596
        - name: fix permissions of password-store
          become: true
          ansible.builtin.file:
            path: "{{ home_path }}/.password-store"
            owner: "{{ user_name }}"
            group: "{{ user_name }}"
            recurse: yes
