#!/usr/bin/env zsh

# Plugin rbenv
# Installation proccess:
#
#  1. Install needed packages
#  2. Link files
#  3. Install plugin gems

source 'helpers/installer_helper.zsh'
PLUGIN_PATH=$0:A:h
DOTFILES_ROOT=$(pwd)

# 1. Clone needed repos
if ! [[ -d ~/.rbenv ]]; then
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  success 'rbenv cloned'
fi

if ! [[ -d ~/.rbenv/plugins/ruby-build ]]; then
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  success 'ruby-build cloned'
fi

# 2. Link files
link_file $PLUGIN_PATH ".gemrc"
link_file $PLUGIN_PATH ".pryrc"

# 3. Install plugin gems
cd $PLUGIN_PATH

# Install ruby
if ! [[ $(rbenv versions | grep $(cat .ruby-version)) ]]; then
  source ./ruby.plugin.zsh
  rbenv install
  success 'ruby installed'
fi

# Ensure we have bundler installed
gem update --system && gem install bundler

# Ensure we have bundler working
rbenv rehash

# Then install the gems listed
update-ruby-packages
