#!/usr/bin/env zsh

# Plugin javascript
# Installation proccess:
#
#  1. Install needed packages
#

source 'helpers/installer_helper.zsh'

if ! [ -d ~/.nodenv ]; then
  git clone https://github.com/nodenv/nodenv.git ~/.nodenv
  success 'nodenv installed'
fi

if ! [ -d ~/.nodenv/plugins/node-build ]; then
  git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build
  success 'node-build installed'
fi
