#!/usr/bin/env zsh

# Plugin javascript
# Installation proccess:
#
#  1. Install nodenv
#  2. Install node
#  3. Install js packages
#

source 'helpers/installer_helper.zsh'
PLUGIN_PATH=$0:A:h

# 1. Install nodenv
if ! [ -d ~/.nodenv ]; then
  git clone https://github.com/nodenv/nodenv.git ~/.nodenv
  success 'nodenv installed'
fi

if ! [ -d ~/.nodenv/plugins/node-build ]; then
  git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build
  success 'node-build installed'
fi

# Link .node-version
link_file $PLUGIN_PATH ".node-version"

cd $PLUGIN_PATH

# 2. Install node
if ! [[ $(nodenv versions | grep $(cat .node-version)) ]]; then
  source ./javascript.plugin.zsh
  nodenv install
  success 'node installed'
fi

# 3. Then install the packages listed on data/packages.txt
update-node-packages
