---
- name: install common desktop packages
  become: true
  register: common_desktop_packages
  community.general.pacman:
    name:
      # Browsers
      - firefox
      - chromium

      # Video players
      - vlc
      - libx264
      - mpv

      # Subtitles editor
      - gaupol

      # Faster camera download
      - rapid-photo-downloader

      # GParted is a GUI partitioner
      - gparted

      # Torrent client
      - transmission-remote-gtk

      # Office tools
      - libreoffice-fresh

      # Fonts
      - ttf-roboto
      - ttf-roboto-mono
      - ttc-iosevka
      - ttf-ibm-plex
      - ttf-opensans
      - otf-fira-sans
      - adobe-source-sans-fonts
      - ttf-croscore
      - noto-fonts-cjk
      - ttf-joypixels
      - ttf-nerd-fonts-symbols

      # Printer drivers
      - cups

      # Scheduler
      - system76-scheduler

      # Tools
      - qalculate-gtk
      - zathura
      - zathura-pdf-mupdf

- name: install desktop packages on AUR
  become: true
  become_user: "{{ user_name }}"
  register: aur_packages
  aur:
    name:
      # Complement for pacman
      - overdue

      # Password managers
      - authy
      - 1password

      # Beancount
      - beancount
      - fava

      # DDC
      - ddccontrol
      - ddccontrol-db-git

      # Spotify
      - spotify

      # Slack/zoom
      - slack-desktop
      - zoom
      - discord

      # Yed
      - yed

      # Fonts
      - ttf-symbola
      - ttf-gelasio-ib
      - ttf-comic-neue

      # psi-notify
      - psi-notify

- name: reload font cache
  become: true
  become_user: "{{ user_name }}"
  when: common_desktop_packages.changed or aur_packages.changed
  ansible.builtin.command: fc-cache -fv

- name: setup system76-scheduler
  become: true
  notify: restart system76-scheduler
  ansible.builtin.copy:
    dest: /etc/system76-scheduler/process-scheduler/custom.kdl
    src: system76-scheduler-custom.kdl

- name: start and enable system76-scheduler at boot time
  become: true
  ansible.builtin.systemd: name=com.system76.Scheduler enabled=yes state=started

- name: start and enable psi-notify at boot time
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.systemd: name=psi-notify enabled=yes state=started scope=user
