---
- name: install common desktop packages
  become: true
  pacman:
    state: present
    name:
      # Browsers
      - firefox
      - chromium

      # VLC
      - vlc
      - libx264

      # mpv for some videos
      - mpv

      # Subtitles editor
      - gaupol

      # Faster camera download
      - rapid-photo-downloader

      # GParted is a GUI partitioner
      - gparted

      # Allow mouting NTFS partitions with read/write
      - ntfs-3g

      # Torrent client
      - transmission-remote-gtk

      # Office tools
      - libreoffice-fresh

      # Wire
      - wire-desktop

      # Fonts
      - ttf-roboto
      - ttf-roboto-mono
      - ttf-croscore
      - noto-fonts-cjk
      - ttf-joypixels

      # ---------------------
      # Packages on AUR/pacom

      # Ananicy
      - ananicy-git

      # Beancount
      - beancount
      - fava

      # Spotify
      - spotify

      # Slack/zoom
      - slack-desktop
      - zoom

      # Yed
      - yed

      # Dropbox
      - dropbox
      - nautilus-dropbox

      # Fonts
      - ttf-symbola
      - ttf-iosevka-term
      - ttf-gelasio-ib
      - ttf-comic-neue
      - ttf-nerd-glyphs
