---
- name: install common desktop packages
  become: true
  register: common_desktop_packages
  community.general.pacman:
    name:
      # Browsers
      - firefox
      - chromium

      # Video players
      - vlc
      - libx264
      - mpv

      # Subtitles editor
      - gaupol

      # Faster camera download
      - rapid-photo-downloader

      # GParted is a GUI partitioner
      - gparted

      # Torrent client
      - transmission-remote-gtk

      # Office tools
      - libreoffice-fresh

      # Fonts
      - ttf-roboto
      - ttf-roboto-mono
      - ttf-croscore
      - noto-fonts-cjk
      - ttf-joypixels
      - ttf-nerd-fonts-symbols

      # Printer drivers
      - cups

      # Tools
      - qalculate-gtk
      - flameshot
      - zathura
      - zathura-pdf-mupdf

- name: install desktop packages on AUR
  become: true
  become_user: "{{ user_name }}"
  register: aur_packages
  aur:
    name:
      # Complement for pacman
      - overdue

      # Password managers
      - authy
      - 1password

      # Beancount
      - beancount
      - fava

      # DDC
      - ddccontrol
      - ddccontrol-db-git

      # Spotify
      - spotify

      # Slack/zoom
      - slack-desktop
      - zoom
      - discord

      # Yed
      - yed

      # Fonts
      - ttf-symbola
      - ttf-iosevka-term
      - ttf-gelasio-ib
      - ttf-comic-neue

- name: reload font cache
  become: true
  become_user: "{{ user_name }}"
  when: common_desktop_packages.changed or aur_packages.changed
  ansible.builtin.command: fc-cache -fv

# TODO: Install ananicy or equivalent such as system76-scheduler
# - name: install psi-notify
#   become: true
#   community.general.pacman: name=psi-notify
#
# - name: start and enable psi-notify at boot time
#   become: true
#   become_user: "{{ user_name }}"
#   ansible.builtin.systemd: name=psi-notify enabled=true state=started scope=user
