---
- name: install common desktop packages
  become: true
  pacman: name={{ item }} state=present
  with_items:
    # Browsers
    - firefox
    - chromium

    # VLC
    - vlc
    - libx264
    # qt4 is an "optional" dependency for vlc, required for GUI usage
    # see: https://wiki.archlinux.org/index.php/VLC_media_player
    - qt4

    # GParted is a GUI partitioner
    - gparted

    # Install OpenVPN NetworkManager plugin
    - networkmanager-openvpn

    # Allow mouting NTFS partitions with read/write
    - ntfs-3g

    # Steam
    - lib32-nvidia-utils
    - steam

    # Torrent client
    - transmission-gtk

    # Office tools
    - libreoffice-fresh

    # Fonts
    - ttf-roboto
    - ttf-croscore

- name: install ttf-nerd-symbols
  become: true
  become_user: "{{ user_name }}"
  command: bin/pkg build --install ttf-nerd-glyphs
  args:
    chdir: /home/{{ user_name }}/Projects/PKGBUILDs

- name: install AUR packages
  become: true
  become_user: "{{ user_name }}"
  command: bin/pkg build --install {{ item }}
  args:
    chdir: /home/{{ user_name }}/Projects/PKGBUILDs
  with_items:
    # Spotify
    - spotify

    # Slack
    - slack-desktop

    # Dropbox
    - dropbox
    - nautilus-dropbox

    # Fonts
    - ttf-symbola
    - ttf-roboto-mono
    - ttf-iosevka-term
    - ttf-gelasio-ib
    - ttf-comic-neue
    - ttf-emojione
