---
- name: install common desktop packages
  become: true
  community.general.pacman:
    name:
      # Browsers
      - firefox
      - chromium

      # Video players
      - vlc
      - libx264
      - mpv

      # Subtitles editor
      - gaupol

      # Faster camera download
      - rapid-photo-downloader

      # GParted is a GUI partitioner
      - gparted

      # Torrent client
      - transmission-remote-gtk

      # Office tools
      - libreoffice-fresh

      # Fonts
      - ttf-roboto
      - ttf-roboto-mono
      - ttf-croscore
      - noto-fonts-cjk
      - ttf-joypixels

      # ---------------------
      # Packages on AUR/pacom
      - overdue # complement for pacman

      # Beancount
      - beancount
      - fava

      # Spotify
      - spotify

      # Slack/zoom
      - slack-desktop
      - zoom

      # Yed
      - yed

      # Dropbox
      - dropbox
      - nautilus-dropbox

      # Fonts
      - ttf-symbola
      - ttf-iosevka-term
      - ttf-gelasio
      - ttf-comic-neue
      - ttf-nerd-glyphs

- name: install ananicy
  become: true
  notify: enable ananicy at boot time
  community.general.pacman: name=ananicy-git

- name: install psi-notify
  become: true
  notify: enable psi-notify at boot time
  community.general.pacman: name=psi-notify
