---
- name: create the system-connections folder
  become: true
  file: path=/etc/NetworkManager/system-connections mode=0700 state=directory

- name: add the vpn network connection
  become: true
  template:
    src: files/vpn-connection.conf
    dest: /etc/NetworkManager/system-connections/Kriansa.nmconnection
    mode: 0600

- name: add the bridge network
  notify: restart network
  become: true
  template:
    src: files/{{ item }}.nmconnection
    dest: /etc/NetworkManager/system-connections/{{ item }}.nmconnection
    mode: 0600
  loop:
    - br0
    - br0-enp0s31f6
