---
- name: create the system-connections folder
  become: true
  file: path=/etc/NetworkManager/system-connections mode=0700 state=directory

- name: add the configured network connections
  notify: restart network
  become: true
  template:
    src: files/{{ item }}.nmconnection
    dest: /etc/NetworkManager/system-connections/{{ item }}.nmconnection
    mode: 0600
  loop:
    - Admin VLAN
