---
- name: create base paths to be mounted on
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file: path={{ home_path }}/{{ item }} state=directory mode=0755
  loop:
    - Drive
    - Media

- name: add media fstab entry
  become: true
  notify: mount drives from fstab
  ansible.builtin.blockinfile:
    path: /etc/fstab
    marker: "# Enable network attached Media ({mark})"
    block: |
      # {{ home_path }}/Media
      {{ shared_drive.media_location }}	{{ home_path }}/Media	cifs	_netdev,vers=3.0,x-gvfs-hide,username=media,password=media,uid={{ user_name }},gid={{ user_name }},iocharset=utf8,noauto,x-systemd.automount,x-systemd.mount-timeout=5,x-systemd.requires=nss-lookup.target,rw	0	0

- name: add drive fstab entry
  become: true
  notify: mount drives from fstab
  ansible.builtin.blockinfile:
    path: /etc/fstab
    marker: "# Enable network attached Drive ({mark})"
    block: |
      # {{ home_path }}/Drive
      {{ shared_drive.drive_location }}	{{ home_path }}/Drive	nfs4	_netdev,x-gvfs-hide,noauto,retry=0,x-systemd.automount,x-systemd.mount-timeout=5,x-systemd.requires=nss-lookup.target,rw	0	0
