---
- name: create a default profile
  become: true
  become_user: "{{ user_name }}"
  shell: firefox -headless -CreateProfile default && timeout 2 firefox -headless || true

- name: get the path of the new profile
  become: true
  become_user: "{{ user_name }}"
  command: grep -Po "(?<=^Default=).*" ~/.mozilla/firefox/installs.ini
  register: profile_name

- set_fact: profile_prefs="~/.mozilla/firefox/{{ profile_name.stdout }}/prefs.js"

# Set the default application for web browsing
# Ref: https://askubuntu.com/questions/16621/how-to-set-the-default-browser-from-the-command-line
- name: make firefox the default application
  become: true
  become_user: "{{ user_name }}"
  shell: xdg-settings set default-web-browser firefox.desktop
