---
- name: add cifs drive credentials file
  become: true
  become_user: "{{ user_name }}"
  copy:
    dest: "{{ home_path }}/.drive-smb-credentials"
    mode: 0600
    content: |
      username={{ shared_drive.username }}
      password={{ shared_drive.password }}

- name: add media fstab entry
  become: true
  blockinfile:
    path: /etc/fstab
    marker: "# Enable network attached Media ({mark})"
    block: |
      # /home/{{ user_name }}/Media
      {{ shared_drive.media_location }}	{{ home_path }}/Media	cifs	_netdev,vers=3.0,x-gvfs-hide,guest,uid={{ user_name }},gid={{ user_name }},iocharset=utf8,noauto,x-systemd.automount,x-systemd.mount-timeout=5,x-systemd.requires=nss-lookup.target,rw	0	0

- name: add drive fstab entry
  become: true
  blockinfile:
    path: /etc/fstab
    marker: "# Enable network attached Drive ({mark})"
    block: |
      # /home/{{ user_name }}/Drive
      {{ shared_drive.drive_location }}	{{ home_path }}/Drive	nfs	_netdev,x-gvfs-hide,noauto,x-systemd.automount,x-systemd.mount-timeout=5,x-systemd.requires=nss-lookup.target,rw	0	0
