#!/usr/bin/env zsh

# Plugin vim
# Installation proccess:
#
#  1. Install needed packages
#  2. Link folder
#

source 'helpers/installer_helper.zsh'
PLUGIN_PATH=$0:A:h
DOTFILES_ROOT=$(pwd)

# 1. Install packages
if [[ $OS_NAME == "OSX" ]]; then
  brew install neovim/neovim/neovim the_silver_searcher
  success 'nvim installed'
fi

# 2. Link files
link_file $PLUGIN_PATH '.config/nvim'

# 3. Run executable
nvim -c PlugInstall -c q -c q
