#!/usr/bin/env zsh

# Plugin tmux
# Installation proccess:
#
#  1. Install needed packages
#  2. Link files
#

source 'helpers/installer_helper.zsh'
PLUGIN_PATH=$0:A:h
DOTFILES_ROOT=$(pwd)

# 1. Install packages
if [[ $OS_NAME == "OSX" ]]; then
  brew install tmux
  success 'tmux installed'
fi

# 2. Link files
link_file $PLUGIN_PATH ".tmux.conf"
link_file $PLUGIN_PATH ".tmux/theme.sh"
