---
- name: install nvim plugins
  become: true
  become_user: "{{ user_name }}"
  command: nvim --headless +PlugInstall +qa

- name: install/update ruby and packages
  become: true
  become_user: "{{ user_name }}"
  shell: eval "$(rbenv init -)" && "{{ playbook_dir | dirname }}/plugins/ruby/bin/update-ruby"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/home/{{ user_name }}/.dotfiles/plugins/ruby/bin"

- name: install/update node and packages
  become: true
  become_user: "{{ user_name }}"
  shell: eval "$(nodenv init -)" && "{{ playbook_dir | dirname }}/plugins/javascript/bin/update-node"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/home/{{ user_name }}/.dotfiles/plugins/javascript/bin"
