---
- stat: path="{{ dotfiles_path }}"
  register: dotfiles_exist

- name: download dotfiles
  become: true
  become_user: "{{ user_name }}"
  when: dotfiles_exist.stat.exists == false
  git:
    repo: https://github.com/kriansa/dotfiles.git
    dest: "{{ dotfiles_path }}"
    update: no

- name: update dotfiles remote to use SSH instead of HTTPS
  become: true
  become_user: "{{ user_name }}"
  command: git remote set-url origin git@github.com:kriansa/dotfiles.git
  args:
    chdir: "{{ dotfiles_path }}"

- name: execute dotup
  become: true
  become_user: "{{ user_name }}"
  command: 
    chdir: "{{ dotfiles_path }}"
    cmd: bin/dotup
