---
# TODO: Arch Linux only. Adapt to work on MacOS.
- stat: path="{{ dotfiles_path }}"
  register: dotfiles_exist

- name: download dotfiles
  become: true
  become_user: "{{ user_name }}"
  when: dotfiles_exist.stat.exists == false
  git:
    repo: https://github.com/kriansa/dotfiles.git
    dest: "{{ dotfiles_path }}"
    update: no

- import_tasks: ansible.yml
- import_tasks: fontconfig.yml
- import_tasks: git.yml
- import_tasks: gpg.yml
- import_tasks: javascript.yml
- import_tasks: nvim.yml
- import_tasks: emacs.yml
- import_tasks: ruby.yml
- import_tasks: gnome.yml
- import_tasks: xorg.yml
- import_tasks: vlc.yml
- import_tasks: rapid-photo-downloader.yml
- import_tasks: zsh.yml

  # Terminal emulator
- import_tasks: tilix.yml

  # Currently I'm good with Tilix. There's another terminal getting traction
  # lately which is Alacritty. Until I find time to experiment it, there's a
  # well configured urxvt available by just uncommenting the line below:
  # - import_tasks: urxvt.yml

- name: update dotfiles remote to use SSH instead of HTTPS
  become: true
  become_user: "{{ user_name }}"
  command: git remote set-url origin git@github.com:kriansa/dotfiles.git
  args:
    chdir: "{{ dotfiles_path }}"
