---
- name: create .config directory
  become: true
  become_user: "{{ user_name }}"
  file: path="{{ home_path }}/.config" state=directory mode=0755

- import_tasks: link_files.yml
  vars:
    plugin_name: nvim
    files:
      - .config/nvim
