---
- name: create .tmux directory
  become: true
  become_user: "{{ user_name }}"
  file: path="{{ home_path }}/.tmux" state=directory mode=0755

- import_tasks: link_files.yml
  vars:
    plugin_name: tmux
    files:
      - .tmux.conf
      - .tmux/theme.sh
