#!/usr/bin/env bash
#
# Desktop Handler for watchpower
# Receives a payload from acpid and automatically configure desktop settings accordingly

rules() {
  case "$1" in
    power-button)
      logger "Power button pressed"
      ;;

    ac-adapter)
      sudo cpupower frequency-set -g performance
      xset dpms 0 0 300
      xbacklight -set 70 -ctrl intel_backlight
      ;;

    battery)
      sudo cpupower frequency-set -g powersave
      xset dpms 0 0 30
      xbacklight -set 30 -ctrl intel_backlight
      ;;

    battery-percentage-10)
      # Popup some alert message
      ;;
    battery-percentage-5)
      # Alert the user that we're hibernating in 5 seconds
      sudo systemctl hibernate
      ;;
  esac
}

# Process every argument individually, in case this gets called with several
for arg in "$@"; do
  rules "$arg"
done
