#!/usr/bin/env bash
#
# Desktop Handler for xorg general settings
# This is called at the start of a X session to setup common or static configs, such as double-click
# delays, cursor shapes, typing rate, etc.

# Default keyboard settings
setxkbmap -model pc104 -layout "us,us" -variant ",alt-intl" -option "grp:caps_toggle"

# Disable screensaver
xset s off off

# Adjust typing delay
xset r rate 300 30
