---
- name: create the system-connections folder
  become: true
  ansible.builtin.file: path=/etc/NetworkManager/system-connections mode=0700 state=directory

- name: configure wifi
  become: true
  when: configure_wifi == true
  community.general.nmcli:
    state: present
    type: wifi
    autoconnect: yes
    ifname: "{{ wifi_device }}"
    conn_name: Wi-Fi
    ssid: "{{ lookup('community.general.passwordstore', 'PC-Config/Wi-Fi-SSID') }}"
    wifi:
      hidden: yes
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ lookup('community.general.passwordstore', 'PC-Config/Wi-Fi-Password') }}"

- name: configure wired network
  become: true
  community.general.nmcli:
    state: present
    type: ethernet
    ifname: "{{ eth_device }}"
    conn_name: Wired-Network
    method4: auto
    method6: auto

- name: remove default network
  community.general.nmcli:
    state: absent
    conn_name: Wired connection 1

- name: configure vlans
  become: true
  community.general.nmcli:
    state: present
    conn_name: "{{ item.name }}"
    type: vlan
    ifname: ""
    vlanid: "{{ item.vlan }}"
    vlandev: "{{ eth_device }}"
    autoconnect: "{{ item.auto }}"
    dns4_ignore_auto: yes
    never_default4: yes
    ip_privacy6: disabled
    # TODO: Add that in the future when it's available on Ansible
    # never_default6: yes
  loop:
    - { name: "Admin", vlan: "1010", auto: true }
    - { name: "IoT", vlan: "1003", auto: false }
    - { name: "External-Services", vlan: "1004", auto: false }

- name: create /etc/wireguard
  become: true
  ansible.builtin.file: path=/etc/wireguard state=directory mode=0700

- name: configure
  ansible.builtin.include_tasks: create_wg_connection.yml
  loop:
    - name: Proxy
      ifname: proxy
      autoconnect: no
      private_key: "{{ lookup('community.general.passwordstore', 'PC-Config/' + secrets_base_dir + '/Proxy/Private-Key') }}"
      addresses: "{{ lookup('community.general.passwordstore', 'PC-Config/' + secrets_base_dir + '/Proxy/Local-IPs') }}"
      peer_public_key: "{{ lookup('community.general.passwordstore', 'Network/Proxy-VPN/Public-Key') }}"
      peer_endpoint: "{{ lookup('community.general.passwordstore', 'Network/Proxy-VPN/Endpoint') }}"
      peer_allowed_ips: 0.0.0.0/0,::0/0

    - name: VPN
      ifname: vpn
      autoconnect: yes
      private_key: "{{ lookup('community.general.passwordstore', 'PC-Config/' + secrets_base_dir + '/VPN/Private-Key') }}"
      addresses: "{{ lookup('community.general.passwordstore', 'PC-Config/' + secrets_base_dir + '/VPN/Local-IPs') }}"
      peer_public_key: "{{ lookup('community.general.passwordstore', 'Network/VPN/Public-Key') }}"
      peer_endpoint: "{{ lookup('community.general.passwordstore', 'Network/VPN/Endpoint') }}"
      peer_allowed_ips: "{{ lookup('community.general.passwordstore', 'Network/VPN/CIDR') }}"
