---
- name: setup links for /etc/resolv.conf
  become: true
  notify: restart systemd-resolved
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    force: yes
    state: link

- name: enable systemd-resolved service
  become: true
  ansible.builtin.systemd: name=systemd-resolved state=started enabled=yes
