#!/usr/bin/env zsh

# Plugin base (required)
# Installation proccess:
#
#  1. Install needed packages
#  2. Link files
#

source 'helpers/installer_helper.zsh'
PLUGIN_PATH=$0:A:h
DOTFILES_ROOT=$(pwd)

# 1. Install packages
if [[ $OS_NAME == "linux" ]]; then
  # Linux
  # TODO
elif [[ $OS_NAME == "OSX" ]]; then
  # Install brew
  if [[ $(type "brew" &> /dev/null; echo $?) != "0" ]]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    # Install homebrew-bundler
    brew tap homebrew/bundle

    # Install homebrew packages
    cd "${PLUGIN_PATH}/data" && brew bundle && cd -
  fi

  # Install fonts
  cp -f ${PLUGIN_PATH}/data/Fonts/**/*.ttf "${HOME}/Library/Fonts"

  success 'Packages installed'
fi

# 2. Link zshrc
link_file $PLUGIN_PATH ".zshrc"
