#!/usr/bin/env zsh

# Plugin base (required)
# Installation proccess:
#
#  1. Install needed packages
#  2. Link files
#

source 'helpers/installer_helper.zsh'
PLUGIN_PATH=$0:A:h
DOTFILES_ROOT=$(pwd)

# 1. Install packages
if [[ $OS_NAME == "linux" ]]; then
  # Linux
  # TODO
elif [[ $OS_NAME == "OSX" ]]; then
  # Install homebrew packages
  brew install ncdu jq tree wrk pstree htop

  # Install fonts
  cp -f "${PLUGIN_PATH}/data/Hack-Font-Powerline/*.ttf" "${HOME}/Library/Fonts"
  cp -f "${PLUGIN_PATH}/data/Knack-Font/*.ttf" "${HOME}/Library/Fonts"

  success 'Packages installed'
fi

# 2. Link zshrc
link_file $PLUGIN_PATH ".zshrc"
