#!/bin/sh
#
# This is a shim for a ruby executable that should always be executed by the Ruby version defined as
# the global one.
#
# It's important so that we don't need to keep installing global gems on every Ruby version that we
# have on our system.

binary=$(basename "$0")

export ASDF_RUBY_VERSION; ASDF_RUBY_VERSION=$(grep '^ruby .*' ~/.tool-versions | awk '{ print $2 }')
status=$?

if [ $status -ne 0 ]; then
  echo "Please set the global ruby version using 'asdf set --home ruby <version>'" && exit 1
fi

shim_path="$(asdf which "$binary")"
exec "$shim_path" "$@"
