# Base16 One Light - alacritty color config
# Daniel Pfeifer (http://github.com/purpleKarrot)
[colors.bright]
black = "#a0a1a7"
blue = "#696c77"
cyan = "#986801"
green = "#8fb399"
magenta = "#202227"
red = "#d75f00"
white = "#090a0b"
yellow = "#e5e5e6"

[colors.cursor]
cursor = "#383a42"
text = "#fafafa"

[colors.normal]
black = "#fafafa"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#ca1243"
white = "#383a42"
yellow = "#c18401"

[colors.primary]
background = "#fafafa"
foreground = "#383a42"
