# Base16 One Light - alacritty color config
# Daniel Pfeifer (http://github.com/purpleKarrot)
[colors.primary]
background = "#fafafa"
foreground = "#383a42"

[colors.cursor]
cursor = "#383a42"
text = "#fafafa"

[colors.bright]
black = "#a0a1a7"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#ca1243"
white = "#090a0b"
yellow = "#c18401"

[colors.normal]
black = "#fafafa"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#ca1243"
white = "#383a42"
yellow = "#c18401"

[[colors.indexed_colors]]
index = 16
color = "#d75f00"

[[colors.indexed_colors]]
index = 17
color = "#986801"

[[colors.indexed_colors]]
index = 18
color = "#f0f0f1"

[[colors.indexed_colors]]
index = 19
color = "#e5e5e6"

[[colors.indexed_colors]]
index = 20
color = "#696c77"

[[colors.indexed_colors]]
index = 21
color = "#202227"
