#!/usr/bin/env zsh

# Plugin pyenv
# Installation proccess:
#
#  1. Install needed packages
#

source 'helpers/installer_helper.zsh'
PLUGIN_PATH=$0:A:h
DOTFILES_ROOT=$(pwd)

# 1. Install from git
if ! [[ -d ~/.pyenv ]]; then
  git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  success 'pyenv cloned'
fi

# Link .python-version
link_file $PLUGIN_PATH ".python-version"
