---
- name: enable libvirtd socket activation
  become: true
  ansible.builtin.systemd: state=restarted enabled=yes name=libvirtd.socket

- name: enable podman.socket so we can use docker-compose
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.systemd: state=restarted enabled=yes scope=user name=podman.socket
