#!/usr/bin/bash
#
# Do the steps needed to fetch the password-store from git repository
#
# IMPORTANT: This script requires interactive shell usage, because it will prompt for passwords.

set -eo pipefail

if [ "$(id -u)" = "0" ]; then
  echo "Don't run this as root!"
  exit 1
fi

if [[ $- != *i* ]]; then
  echo "This script needs to be run interactively because it prompts for passwords!"
  exit 1
fi

# We need root permissions to assign the current TTY to the running user
sudo chown $(id -u) $(tty)

# Then first we adjust the Pinentry TTY
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye > /dev/null 2>&1

# Add our git server to known_hosts
test -d ~/.ssh || mkdir -m 700 ~/.ssh
touch ~/.ssh/known_hosts
ssh-keyscan git.lan.cx 2> /dev/null | sort -u ~/.ssh/known_hosts - > ~/.ssh/known_hosts

# Now ensure we have our GPG private key installed
echo "Ensure your Yubikey is inserted and press enter to continue"
read -p ""
curl https://garajau.com.br/pgp.asc | gpg --import && gpg --card-status

# Then fetch it from git
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
cd && git clone git@git.lan.cx:.password-store.git
