#!/usr/bin/env sh
#
# This is a shim for a ruby executable that should always be executed by the Ruby version defined as
# the global one.
#
# It's important so that we don't need to keep installing global gems on every Ruby version that we
# have on our system.
#
# Works with rbenv. To use it just link it to the name of the gem binary you want to execute.

# Remove this bin dir from $PATH env var
# So we don't end up in a infinite loop
THIS_DIR=$(cd "$(dirname "$0")" || exit; pwd)
export PATH; PATH=$(echo "$PATH" | sed -e "s#${THIS_DIR}:##")

# Set the ruby version to the global one
export RBENV_VERSION; RBENV_VERSION=$(rbenv global)

# Then execute the original binary file
binary=$(basename "$0")
$binary "$@"
