#!/usr/bin/env zsh

# Plugin base update process
#
source 'helpers/installer_helper.zsh'

# upgrade_oh_my_zsh
env ZSH=$ZSH sh $ZSH/tools/upgrade.sh

if [[ $OS_NAME == "linux" ]]; then
  # Linux
  # TODO
elif [[ $OS_NAME == "OSX" ]]; then
  # Install homebrew packages
  brew update && brew upgrade
fi
