---
- hosts: all
  vars_prompt:
    - name: restore_data
      prompt: "Should we also restore data from latest backup?"
      default: no

  roles:
    - role: 1-common-handlers
    - role: base-arch
    - role: systemd-boot
    - role: aur-manager
    - role: dev-tools
    - role: borgmatic
    - role: yubikey
    - role: network
    - role: gnome
    - role: desktop-tools
