---
- hosts: all
  vars_prompt:
    - name: restore_data
      prompt: Should we also restore data from latest backup?
      private: no
      default: no

  vars:
    hostname: daniel-desktop.lan.cx

    install_amd_drivers: true
    install_nvidia_drivers: true
    enable_bluetooth: true
    cpu_brand: amd

  roles:
    - role: 1-common-handlers
    - role: base-arch
    - role: systemd-boot
    - role: aur-manager
    - role: dev-tools
    - role: yubikey
    - role: network
    - role: kde
    - role: desktop-tools
    - role: borgmatic
