---
- hosts: all

  roles:
  - role: base-arch
  - role: systemd-boot
  - role: nvidia
  - role: gnome
  - role: desktop-tools
  - role: borgmatic
  - role: yubikey
  - role: dev-tools
  - role: dotfiles
