---
- hosts: all
  roles:
    - role: 1-common-handlers
    - role: base-arch
    - role: systemd-boot
    - role: aur-manager
    - role: dev-tools
    - role: borgmatic
    - role: yubikey

    # NOT validated
    # - role: syncthing

    - role: network
    - role: gnome
    - role: desktop-tools # TODO: setup Firefox and Ananicy
