---
- hosts: all
  vars_prompt:
    - name: restore_data
      prompt: Should we also restore data from latest backup?
      private: no
      default: no

  vars:
    hostname: daniel-laptop.lan.cx

    install_intel_drivers: true
    install_nvidia_drivers: true
    enable_bluetooth: true
    cpu_brand: intel
    encrypt_disk: true

    # Enable Wi-fi
    configure_wifi: true
    wifi_device: wlp0s20f3
    eth_device: enp3s0

    config_file_suffix: laptop
    secrets_base_dir: Laptop

  roles:
    - role: 1-common-handlers
    - role: base-arch
    - role: systemd-boot
    - role: aur-manager
    - role: dev-tools
    - role: yubikey
    - role: network
    - role: kde
    - role: desktop-tools
    - role: borgmatic

  tasks:
    - name: install extra packages
      become: true
      community.general.pacman:
        name:
          - fwupd
