---
- hosts: all
  vars:
    hostname: daniel-laptop.lan.cx
    # Check if that is going to be an issue
    disable_nvidia_i2c: false

    # Configure onboard intel gpu drivers
    install_intel_drivers: true

    # Encrypted partitioning options
    encrypt_disk: true
    encrypted_partition_uuid: 571e47d1-cb34-41d9-a271-7fb6b2a47c3f
    lvm_vg_name: vg0

    # Enable Wi-fi
    configure_wifi: yes
    wifi_device: wlp0s20f3
    eth_device: enp0s13f0u1c2

    # For all machine-dependent config files, append this suffix to determine which one to use
    config_file_suffix: laptop

    # Specific path when looking for secrets for this machine specifically
    secrets_base_dir: Laptop

  roles:
    - role: base-arch
    # - role: systemd-boot
    # - role: secrets
    # - role: network
    - role: dev-tools
    - role: borgmatic
    - role: desktop-tools
    - role: gnome
