---
- name: add i2c group
  become: true
  ansible.builtin.group:
    name: i2c
    state: present
    system: yes

- name: add my user to the i2c group
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: i2c
    append: yes
