---
- name: add user
  become: true
  register: add_user
  ansible.builtin.user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    groups: wheel,uucp
    append: yes
    shell: /usr/bin/fish
    update_password: on_create
    password: "{{ '123' | password_hash('sha512') }}"

- when: add_user.changed
  ansible.builtin.debug:
    msg: "Please, change the password of the user {{ user_name }}! (default is '123')"

- name: ensure that users on wheel group have sudo access
  become: true
  ansible.builtin.copy: src=files/10-wheel.conf dest=/etc/sudoers.d/10-wheel mode=0440

- name: lock root password
  become: true
  ansible.builtin.user:
    name: root
    password_lock: true

- name: check for lingering
  ansible.builtin.command: loginctl show-user "{{ user_name }}" --property=Linger 2>/dev/null | grep -q 'yes'
  register: result
  failed_when: ( result.rc not in [ 0, 1 ] )

- name: enable lingering
  when: result.rc == 1
  ansible.builtin.shell: systemctl restart systemd-logind && loginctl enable-linger "{{ user_name }}"

- name: create user base paths
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    state: directory
    mode: "{{ item.mode }}"
    dest: "{{ home_path }}/{{ item.path }}"
  loop:
    - { path: .config, mode: "0755" }
    - { path: .local, mode: "0700" }
    - { path: .local/share, mode: "0700" }
    - { path: .gnupg, mode: "0700" }
