---
- name: add user
  become: true
  register: add_user
  ansible.builtin.user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    # https://wiki.archlinux.org/index.php/users_and_groups
    groups: wheel,log,systemd-journal,uucp
    shell: /usr/bin/fish
    # Set the password to "123" so we can log in using GDM
    # Then, it's advised that we should change this password.
    update_password: on_create
    password: "{{ '123' | password_hash('sha512', 'mysecretsalt') }}"

- when: add_user.changed
  ansible.builtin.debug:
    msg: "Please, change the password of the user {{ user_name }}! (default is '123')"

- name: ensure that users on wheel group have sudo access
  become: true
  ansible.builtin.copy: src=files/10-wheel.conf dest=/etc/sudoers.d/10-wheel mode=0440

- name: lock root password
  become: true
  ansible.builtin.user:
    name: root
    password_lock: true

- name: check for lingering
  ansible.builtin.command: loginctl show-user "{{ user_name }}" --property=Linger 2>/dev/null | grep -q 'yes'
  register: result
  failed_when: ( result.rc not in [ 0, 1 ] )

- name: enable lingering
  when: result.rc == 1
  ansible.builtin.command: loginctl enable-linger "{{ user_name }}"
