---
- name: create folder for custom repository
  become: true
  file: path=/var/cache/pacman/custom state=directory mode=0755 owner={{ user_name }} group={{ user_name }}

- name: create custom repository
  become: true
  become_user: "{{ user_name }}"
  shell: repo-add /var/cache/pacman/custom/git.db.tar
  args:
    creates: /var/cache/pacman/custom/git.db.tar

- name: add custom git repository to pacman
  become: true
  blockinfile:
    path: /etc/pacman.conf
    marker: "# Enable Custom Git repository ({mark})"
    block: |
      [git]
      SigLevel = Optional TrustAll
      Server = file:///var/cache/pacman/custom

- name: update repo db
  become: true
  pacman:
    update_cache: yes

- name: clones my PKGBUILDs git repo
  become: true
  become_user: "{{ user_name }}"
  git:
    repo: https://github.com/kriansa/PKGBUILDs
    dest: /home/{{ user_name }}/Projects/PKGBUILDs

- name: update PKGBUILDs remote to use SSH instead of HTTPS
  become: true
  become_user: "{{ user_name }}"
  command: git remote set-url origin git@github.com:kriansa/PKGBUILDs.git
  args:
    chdir: /home/{{ user_name }}/Projects/PKGBUILDs
