---
- name: enable ntp servers for systemd-timesyncd
  become: true
  copy: src=files/timesyncd.conf dest=/etc/systemd/timesyncd.conf mode=0644

- name: enable ntp synchronization
  become: true
  command: timedatectl set-ntp true

- name: set timezone
  become: true
  community.general.timezone:
    name: America/Sao_Paulo
    hwclock: UTC
