---
- name: create journald drop-in directory
  become: true
  ansible.builtin.file: path=/etc/systemd/journald.conf.d state=directory

- name: limit journal log retention size
  become: true
  notify: restart systemd-journald
  ansible.builtin.copy:
    dest: /etc/systemd/journald.conf.d/01-limit-space.conf
    content: |
      [Journal]
      SystemMaxUse=50M
