---
- name: add pacman hook to update mirrorlist on upgrades
  become: true
  ansible.builtin.copy: src=files/mirrorupgrade.hook dest=/etc/pacman.d/hooks/mirrorupgrade.hook mode=0644

- name: add pacman hook to cleanup the cache
  become: true
  ansible.builtin.copy: src=files/pacman-cache-cleanup.hook dest=/etc/pacman.d/hooks/pacman-cache-cleanup.hook mode=0644

- name: enable sending logs to journald
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?UseSyslog'
    line: 'UseSyslog'

- name: enable colors
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?Color'
    line: 'Color'

- name: enable parallel downloads
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?ParallelDownloads'
    line: 'ParallelDownloads = 5'

- name: install pacman helpers to enhance pacman experience
  become: true
  community.general.pacman:
    name:
      - reflector            # to update the mirrorlist with the best mirrors
      - rebuild-detector     # detect packages that needs rebuild
      - pacman-contrib       # extra tools for pacman
