---
- name: create base paths on Home folder
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file: path=/home/{{ user_name }}/{{ item }} state=directory mode=0755
  loop:
    - Drive
    - Downloads
    - Projects
    - Media
