---
- name: create base paths on Home folder
  become: true
  become_user: "{{ user_name }}"
  file: path=/home/{{ user_name }}/{{ item }} state=directory mode=0755
  loop:
    - Drive
    - Downloads
    - Projects

- name: link media external drive to the home folder
  become: true
  become_user: "{{ user_name }}"
  file:
    src: "{{ home_path }}/Drive/Media"
    dest: "{{ home_path }}/Media"
    state: link
    force: yes
