---
# PulseAudio enables by default "deferred volume", which is a way to overcome some issues caused by
# the "flat volume" configuration enabled by default on most distros.
# One of the side effects of deferred volume is a small delay while changing the volume of the HW
# output. On Arch, flat volume is disabled, so it doesn't make sense to keep deferred volume on as
# well.
#
# See: https://community.spotify.com/t5/Desktop-Linux/Delay-when-changing-volume/m-p/1843731#M2065
# See: https://manpages.ubuntu.com/manpages/precise/man5/pulse-daemon.conf.5.html#default%20deferred%20volume%20settings
# See: https://bugs.archlinux.org/task/46904
- name: disable deferred volume on PulseAudio
  become: true
  notify: restart pulseaudio
  lineinfile:
    line: "enable-deferred-volume = no"
    path: /etc/pulse/daemon.conf
    insertbefore: "^; enable-deferred-volume"
