---
- name: install default locale
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: set locale to /etc/locale.conf
  become: true
  ansible.builtin.copy:
    content: "LANG={{ arch_locale }}"
    dest: /etc/locale.conf

- name: set vconsole keymap
  become: true
  notify: rebuild initramfs
  ansible.builtin.copy:
    content: "KEYMAP={{ arch_keymap }}"
    dest: /etc/vconsole.conf

- name: set the hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
