---
- name: install default locale
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: set locale to /etc/locale.conf
  become: true
  ansible.builtin.copy:
    content: "LANG={{ arch_locale }}"
    dest: /etc/locale.conf

- name: set vconsole keymap
  become: true
  notify: rebuild initramfs
  ansible.builtin.copy:
    content: "KEYMAP={{ arch_keymap }}"
    dest: /etc/vconsole.conf

- name: set the hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: extract hostname without domain
  ansible.builtin.set_fact:
    short_hostname: "{{ hostname.split('.')[0] }}"

- name: add hostnames to /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127\\.0\\.0\\.1\\s+{{ item }}$"
    line: "127.0.0.1 {{ item }}"
    state: present
  loop:
    - "{{ hostname }}"
    - "{{ short_hostname }}"

- name: enable ntp synchronization
  become: true
  ansible.builtin.command: timedatectl set-ntp true

- name: set timezone
  become: true
  community.general.timezone:
    name: "{{ arch_timezone }}"
    hwclock: UTC
