---
- name: create /etc/pacman.d/hooks directory
  become: true
  ansible.builtin.file: path=/etc/pacman.d/hooks state=directory mode=0755

- name: update system
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: install base packages
  become: true
  notify: restart dbus
  community.general.pacman:
    name:
      - linux
      - linux-lts
      - base-devel
      - nftables
      - wireguard-tools
      - usbutils
      - sudo
      - avahi
      - pulseaudio
      - wget
      - openbsd-netcat
      - openssh
      - python
      - git
      - fish
      - rsync
      - nfs-utils
      - cifs-utils
      - ntfs-3g
      - gnupg
      - btop
      - htop
      - unzip
      - unrar
      - xz
      - p7zip
      - zip
      - hdparm
      - lsof
      - ldns         # for drill tool (dig with DNSSEC)

# no downtime on kernel updates
- name: install kernel-modules-hook
  become: true
  notify: enable kernel modules hook
  community.general.pacman: name=kernel-modules-hook

- meta: flush_handlers
