---
- name: update system
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: create /etc/pacman.d/hooks directory
  become: true
  file: path=/etc/pacman.d/hooks state=directory mode=0755

- name: install base packages
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - sudo
    - wget
    - openssh
    - python
    - git
    - zsh
    - gnupg
    - tree
    - htop
    - unzip
    - unrar
    - xz
    - p7zip
    - bind-tools # dig
    - ldns # for drill tool (dig with DNSSEC)
