---
- name: install nvidia drivers
  become: true
  community.general.pacman:
    state: present
    name:
      - nvidia
      - nvidia-lts
      - nvidia-settings
      - mesa-utils
      # A translation layer between the Intel Acceleration API (VA-API) and NVIDIA (VDPAU)
      - libva-vdpau-driver

- name: add nvidia kernel parameter to use DRM mode
  become: true
  notify: rebuild initramfs
  ansible.builtin.copy: dest=/etc/modprobe.d/nvidia.conf src=modprobe-nvidia.conf

- name: disable nvidia i2c modules
  become: true
  notify: rebuild initramfs
  when: disable_nvidia_i2c == true
  ansible.builtin.copy: dest=/etc/modprobe.d/nvidia-blacklist-i2c.conf src=nvidia-blacklist-i2c.conf

- name: create path for nvidia-xdriver on boot
  become: true
  ansible.builtin.copy:
    dest: /etc/tmpfiles.d/nvidia.conf
    content: d /run/nvidia-xdriver 0777 root root

- name: create path for nvidia-xdriver
  become: true
  ansible.builtin.file:
    mode: "0777"
    dest: /run/nvidia-xdriver
    state: directory

- name: add device config for nvidia on xorg
  become: true
  ansible.builtin.copy:
    dest: /etc/X11/xorg.conf.d/20-nvidia-device.conf
    content: |
      Section "Device"
        Identifier   "nvidia-gpu"
        Driver       "nvidia"
        VendorName   "NVIDIA Corporation"
        BusID        "PCI:1:0:0"
        Option       "ConnectToAcpid" "0"
        Option       "SidebandSocketPath" "/run/nvidia-xdriver"
      EndSection

- name: enable nvidia power-related services
  become: true
  ansible.builtin.systemd:
    enabled: yes
    name: "{{ item }}"
  loop:
    - nvidia-suspend
    - nvidia-hibernate
