---
- name: create /etc/pacman.d/hooks directory
  become: true
  file: path=/etc/pacman.d/hooks state=directory mode=0755

- name: enable multilib packages for pacman
  become: true
  blockinfile:
    path: /etc/pacman.conf
    marker: "# Enable 32-bits libraries ({mark})"
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

# TODO: Once this repo gets signed packages, remove the SigLevel line
- name: add kriansa aur repository to pacman
  become: true
  blockinfile:
    path: /etc/pacman.conf
    marker: "# Enable Kriansa AUR repository ({mark})"
    block: |
      [aur-kriansa]
      Server = https://aur.garajau.com.br/
      SigLevel = Never

- name: update system
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: install base packages
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - sudo
    - wget
    - openssh
    - python
    - git
    - zsh
    - gnupg
    - tree
    - htop
    - unzip
    - unrar
    - xz
    - p7zip
    - bind-tools # dig
    - ldns # for drill tool (dig with DNSSEC)
