---
- name: install nvidia drivers
  become: true
  community.general.pacman:
    state: present
    name:
      - nvidia
      - nvidia-lts
      - nvidia-settings
      # A translation layer between the Intel Acceleration API (VA-API) and NVIDIA (VDPAU)
      - libva-vdpau-driver

- name: add nvidia kernel parameter to use DRM mode
  become: true
  notify: rebuild initramfs
  ansible.builtin.copy: dest=/etc/modprobe.d/nvidia.conf src=modprobe-nvidia.conf

- name: disable nvidia i2c modules
  become: true
  notify: rebuild initramfs
  when: disable_nvidia_i2c == true
  ansible.builtin.copy: dest=/etc/modprobe.d/nvidia-blacklist-i2c.conf src=nvidia-blacklist-i2c.conf

- name: add nvidia-generated xorg configuration for my monitor
  become: true
  ansible.builtin.copy: dest=/etc/X11/xorg.conf.d/01-monitor.conf src={{ xorg_monitor_file }}

- name: enable nvidia power-related services
  become: true
  ansible.builtin.systemd:
    enabled: yes
    name: "{{ item }}"
  loop:
    - nvidia-suspend
    - nvidia-hibernate
