---
- name: create /etc/pacman.d/hooks directory
  become: true
  file: path=/etc/pacman.d/hooks state=directory mode=0755

- name: enable multilib packages for pacman
  become: true
  blockinfile:
    path: /etc/pacman.conf
    marker: "# Enable 32-bits libraries ({mark})"
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: update system
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: install base packages
  become: true
  notify: restart dbus
  pacman: 
    state: present
    name:
      - base-devel
      - sudo
      - wget
      - openssh
      - python
      - git
      - zsh
      - rsync
      - gnupg
      - tree
      - htop
      - unzip
      - unrar
      - xz
      - p7zip
      - zip
      - bind-tools   # dig
      - ldns         # for drill tool (dig with DNSSEC)
      - xclip        # for interaction with the clipboard

- name: install avahi
  become: true
  notify: restart dbus
  pacman: name=avahi state=present

- meta: flush_handlers
