---
- name: check if aurutils is already installed
  command: which aur
  ignore_errors: true
  register: which_aurutils

# Only proceeds wipikaurth the installation if `which aurutils` returns an error
# (i.e. return code == 1), meaning that it hasn't been isntalled yet.
- set_fact: should_install_aurutils={{ which_aurutils.rc == 1 }}

- name: install required dependencies
  become: true
  pacman: name={{ item }} state=present
  when: should_install_aurutils == true
  with_items:
    - jq
    - pacutils
    - vifm

- name: create tmp folder to build aurutils
  become: true
  become_user: "{{ user_name }}"
  when: should_install_aurutils == true
  file: path=/tmp/aurutils_build state=directory mode=0755

- name: download the PKGBUILD file from AUR
  become: true
  become_user: "{{ user_name }}"
  when: should_install_aurutils == true
  get_url:
    url: https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=aurutils-git
    dest: /tmp/aurutils_build
    mode: 0644

- name: build and install aurutils
  become: true
  become_user: "{{ user_name }}"
  when: should_install_aurutils == true
  command: makepkg -p aurutils-git-PKGBUILD --clean --install --needed --noconfirm
  args:
    chdir: /tmp/aurutils_build
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

- name: delete the tmp folder
  become: true
  become_user: "{{ user_name }}"
  when: should_install_aurutils == true
  file: path=/tmp/aurutils_build state=absent
