---
- name: install nvidia drivers
  become: true
  pacman:
    state: present
    name:
      - libglvnd
      - nvidia
      - nvidia-lts
      - nvidia-settings
      - libva-vdpau-driver

- name: add nvidia kernel parameter to use DRM mode
  become: true
  notify: rebuild initramfs
  copy: dest=/etc/modprobe.d/nvidia.conf src=files/modprobe-nvidia.conf mode=0644

- name: add nvidia-generated xorg configuration for my monitor
  become: true
  copy: dest=/etc/X11/xorg.conf.d/01-monitor.conf src=files/xorg-monitor.conf

- name: enable nvidia power-related services
  become: true
  systemd:
    enabled: yes
    name: "{{ item }}"
  loop:
    - nvidia-suspend
    - nvidia-hibernate
