---
- name: install nvidia drivers
  become: true
  community.general.pacman:
    state: present
    name:
      - nvidia
      - nvidia-lts
      - nvidia-settings
      - mesa-utils
      # A translation layer between the Intel Acceleration API (VA-API) and NVIDIA (VDPAU)
      - libva-vdpau-driver

- name: add nvidia kernel parameter to use DRM mode
  become: true
  notify: rebuild initramfs
  ansible.builtin.copy: dest=/etc/modprobe.d/nvidia.conf src=modprobe-nvidia.conf

- name: disable nvidia i2c modules
  become: true
  notify: rebuild initramfs
  when: disable_nvidia_i2c == true
  ansible.builtin.copy: dest=/etc/modprobe.d/nvidia-blacklist-i2c.conf src=nvidia-blacklist-i2c.conf

- name: create path for nvidia-xdriver on boot
  become: true
  ansible.builtin.copy:
    dest: /etc/tmpfiles.d/nvidia.conf
    content: d /run/nvidia-xdriver 0770 root wheel

- name: create path for nvidia-xdriver
  become: true
  ansible.builtin.file:
    mode: "0770"
    owner: root
    group: wheel
    path: /run/nvidia-xdriver

- name: add nvidia-generated xorg configuration for my monitor
  become: true
  ansible.builtin.copy:
    dest: /etc/X11/xorg.conf.d/01-monitor.conf
    src: xorg-monitor-{{ config_file_suffix }}.conf

- name: enable nvidia power-related services
  become: true
  ansible.builtin.systemd:
    enabled: yes
    name: "{{ item }}"
  loop:
    - nvidia-suspend
    - nvidia-hibernate
