---
- name: create /etc/pacman.d/hooks directory
  become: true
  file: path=/etc/pacman.d/hooks state=directory mode=0755

- name: update system
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: install base packages
  become: true
  notify: restart dbus
  pacman:
    state: present
    name:
      - linux
      - linux-lts
      - base-devel
      - pacman-contrib
      - sudo
      - wget
      - openbsd-netcat
      - openssh
      - python
      - git
      - zsh
      - rsync
      - nfs-utils
      - gnupg
      - tree
      - htop
      - unzip
      - unrar
      - xz
      - p7zip
      - zip
      - hdparm
      - bind-tools   # dig
      - ldns         # for drill tool (dig with DNSSEC)
      - xclip        # for interaction with the clipboard
      - reflector    # to update the mirrorlist with the best mirrors

- name: install avahi
  become: true
  notify: restart dbus
  pacman: name=avahi state=present

- meta: flush_handlers
