---
- import_tasks: initial_setup.yml
- import_tasks: adjust_ntp.yml
- import_tasks: configure_pacman.yml
- import_tasks: install_base_packages.yml
- import_tasks: add_user.yml
- import_tasks: install_pacom.yml
- import_tasks: create_base_paths.yml
- import_tasks: enable_basic_services.yml
- import_tasks: allow_mounting_partitions.yml
- import_tasks: configure_journal.yml
- import_tasks: install_nvidia.yml
