---
- name: install nvidia drivers
  become: true
  pacman:
    state: present
    name:
      - libglvnd
      - nvidia
      - nvidia-lts
      - nvidia-settings
      - libva-vdpau-driver

- name: add nvidia kernel parameter to use DRM mode (for systemd-boot)
  become: true
  when: "'systemd-boot' in role_names"
  lineinfile:
    path: /boot/loader/entries/arch.conf
    regexp: "^options (.*)$"
    line: 'options \1 nvidia-drm.modeset=1'
    backrefs: yes

- name: add nvidia modules to initramfs modules
  become: true
  notify: rebuild initramfs
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: 'MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)'

- name: add pacman hook to update initramfs on upgrades
  become: true
  copy: src=files/nvidia.hook dest=/etc/pacman.d/hooks/nvidia.hook mode=0644
