---
- name: install libvirt
  become: true
  pacman: 
    state: present
    name:
      - qemu
      - virt-manager
      - ebtables
      - dnsmasq
      - dmidecode # This is an optional dependency for libvirtd
