---
- name: install podman packages
  become: true
  community.general.pacman:
    state: present
    name:
      - podman
      - podman-docker
      - crun
      - docker-compose
      - netavark
      - aardvark-dns
      - fuse-overlayfs

- name: add uids to /etc/subuid
  become: true
  ansible.builtin.lineinfile: create=yes path=/etc/subuid line="{{ user_name }}:10000:65536"

- name: add uids to /etc/subgid
  become: true
  ansible.builtin.lineinfile: create=yes path=/etc/subgid line="{{ user_name }}:10000:65536"

- name: create /etc/containers/nodocker
  become: true
  ansible.builtin.file: path=/etc/containers/nodocker state=touch modification_time=preserve access_time=preserve

- name: enable podman.socket so we can use docker-compose
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.systemd: state=restarted enabled=yes scope=user name=podman.socket
