---
- name: set the default rbenv version to {{ ruby_version }}
  become: true
  become_user: "{{ user_name }}"
  lineinfile:
    path: "{{ home_path }}/.rbenv/version"
    line: "{{ ruby_version }}"
    state: present
    create: true
    mode: 0644

- name: install ruby {{ ruby_version }}
  become: true
  become_user: "{{ user_name }}"
  command: "rbenv install {{ ruby_version }}"
  args:
    creates: "{{ home_path }}/.rbenv/versions/{{ ruby_version }}"

- name: install/update ruby packages
  become: true
  become_user: "{{ user_name }}"
  shell: eval "$(rbenv init -)" && "{{ playbook_dir | dirname }}/plugins/ruby/bin/update-ruby-packages"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin"
