---
- name: install libvirt
  become: true
  notify: enable libvirtd socket activation
  community.general.pacman:
    state: present
    name:
      - qemu
      - qemu-ui-gtk
      - virt-manager
      - dnsmasq
      - swtpm     # This is necessary to enable TPM module to VMs
      - dmidecode # This is an optional dependency for libvirtd

- name: add {{ user_name }} to group libvirt
  become: true
  ansible.builtin.user: name={{ user_name }} groups=libvirt append=yes
