---
- name: create /var/lib/docker directory
  become: true
  file: path="/var/lib/docker" state=directory mode=0711

# See details of fstab syntax below
# https://wiki.archlinux.org/index.php/fstab
#
# The x-systemd.device-timeout=60s flag instructs systemd to wait for the disk
# to be ready before proceding. This is important because HDD disks might be
# slower than the SSD boot device.
#
# ref: https://www.suse.com/support/kb/doc/?id=7018491
- name: mount disk partition to /var/lib/docker
  become: true
  mount:
    path: /var/lib/docker
    src: UUID={{ docker_partition_uuid }}
    fstype: ext4
    opts: rw,relatime,data=ordered,x-systemd.device-timeout=60s
    dump: 0
    passno: 2
    state: present

- name: install docker packages
  become: true
  pacman: name={{ item }} state=present
  loop:
    - docker
    - docker-compose

- name: add existing user "{{ user_name }}" to group docker
  become: true
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes

- name: enable docker at startup
  become: true
  systemd: state=enabled name=docker
