---
- name: install libvirt
  become: true
  notify: enable libvirtd socket activation
  pacman:
    state: present
    name:
      - qemu
      - virt-manager
      - ebtables
      - dnsmasq
      - dmidecode # This is an optional dependency for libvirtd
