---
- name: install podman packages
  become: true
  pacman:
    state: present
    name:
      - podman
      - docker-compose
      - cni-plugin-dnsname

      # Currently, two bugs prevent me to fully use `podman` as `docker` replacement. See: bugs.md
      # When those are fixed, then replace `docker` by `podman-docker`
      # - podman-docker
      - docker

- name: add uids to /etc/subuid
  become: true
  lineinfile: create=yes path=/etc/subuid line="{{ user_name }}:10000:65536"

- name: add uids to /etc/subgid
  become: true
  lineinfile: create=yes path=/etc/subgid line="{{ user_name }}:10000:65536"

- name: create /etc/containers/nodocker
  become: true
  file: path=/etc/containers/nodocker state=touch modification_time=preserve access_time=preserve

# When podman issues gets fixed (see bugs.md) then uncomment this and remove the docker task below
# - name: enable podman.socket so we can use docker-compose
#   become: true
#   systemd: state=started enabled=yes name=podman.socket
- name: enable docker.socket so we can use docker-compose
  become: true
  systemd: state=started enabled=yes name=docker.socket
