---
- name: set the default nodenv version to {{ node_version }}
  become: true
  become_user: "{{ user_name }}"
  lineinfile: 
    path: "{{ home_path }}/.nodenv/version" 
    line: "{{ node_version }}" 
    state: present
    create: true
    mode: 0644

- name: install node {{ node_version }}
  become: true
  become_user: "{{ user_name }}"
  command: "nodenv install {{ node_version }}"
  args:
    creates: "{{ home_path }}/.nodenv/versions/{{ node_version }}"

- name: install/update node packages
  become: true
  become_user: "{{ user_name }}"
  shell: eval "$(nodenv init -)" && "{{ dotfiles_path }}/plugins/javascript/bin/update-node-packages"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin"
