---
- name: enable u2f login for gdm
  lineinfile:
    path: /etc/pam.d/gdm-password
    line: auth       sufficient                  pam_u2f.so nouserok cue
    insertbefore: auth       include                     system-local-login

- name: enable u2f login for sudo
  lineinfile:
    path: /etc/pam.d/sudo
    line: auth		sufficient	pam_u2f.so nouserok cue
    insertbefore: auth		include		system-auth

- name: enable u2f login for policykit
  lineinfile:
    path: /etc/pam.d/sudo
    line: auth       sufficient   pam_u2f.so nouserok cue
    insertbefore: auth       include      system-auth
