---
- name: enable u2f login for system auth
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/system-auth
    line: auth       sufficient                  pam_u2f.so cue origin=pam://{{ user_name }}
    insertafter: auth       required                    pam_faillock.so      preauth
