---
- name: install yubikey manager
  become: true
  pacman: name=yubikey-manager state=present

- name: install smartcard libs/tools
  become: true
  pacman: name={{ item }} state=present
  loop:
    - pcsclite
    - libusb-compat
    - ccid

- name: enable pcscd service
  become: true
  systemd: name=pcscd enabled=true
