---
- name: install yubikey software
  become: true
  pacman: 
    state: present
    name: 
      - yubikey-manager 
      - pam-u2f

- name: install smartcard libs/tools
  become: true
  pacman: 
    state: present
    name:
      - pcsclite
      - libusb-compat
      - ccid

- name: enable pcscd service
  become: true
  systemd: name=pcscd enabled=true
