---
- name: verify yubikey
  tags: interactive
  ansible.builtin.pause:
    prompt: Please, insert your YubiKey
    seconds: 30

- name: ack private gpg from the card
  tags: interactive
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: gpg --card-status
  ignore_errors: yes

- name: create ~/.config/Yubico folder
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    mode: "0700"
    dest: "{{ home_path }}/.config/Yubico"
    state: directory

- name: ack private gpg from the card (touch your yubikey flashing)
  tags: interactive
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: pamu2fcfg --origin=pam://{{ user_name }} > ~/.config/Yubico/u2f_keys
  ignore_errors: yes
