---
- name: restart network
  become: true
  systemd: state=restarted name=NetworkManager

- name: enable psi-notify at boot time
  become: true
  become_user: "{{ user_name }}"
  systemd: name=psi-notify enabled=true state=started scope=user

- name: enable ananicy at boot time
  become: true
  systemd: name=ananicy enabled=true state=started
