#!/usr/bin/env bash
#
# Desktop Handler for inputplug
# Receives a payload from inputplug and automatically configure the device accordingly

# We only care about enabled devices
[ "$1" != "XIDeviceEnabled" ] && exit

id="$2"
type="$3"
name="$4"

case "$type:$name" in
  XISlaveKeyboard:*)
    setxkbmap -model pc104 -layout "us,us" -variant ",alt-intl" -option "" -option "grp:caps_toggle"
    xset r rate 300 30
    ;;& # bashism: test next pattterns

  XISlavePointer:"Razer Razer DeathAdder V2")
    xinput set-prop "$id" "libinput Accel Speed" -0.800000
    ;;

  XISlavePointer:"DELL0A71:00 04F3:317E Touchpad")
    xinput set-prop "$id" "libinput Tapping Enabled" 1
    xinput set-prop "$id" "libinput Natural Scrolling Enabled" 1
    xinput set-prop "$id" "libinput Tapping Drag Lock Enabled" 1
    ;;
esac
