#!/usr/bin/env bash
#
# Desktop Handler for watchpower
# Receives a payload from acpid and automatically configure desktop settings accordingly

rules() {
  case "$1" in
    power-button)
      logger "Power button pressed"
      ;;

    ac-adapter)
      sudo cpupower frequency-set -g performance
      xset s 300
      xbacklight -set 70 -ctrl intel_backlight
      ;;

    battery)
      sudo cpupower frequency-set -g powersave
      xset s 60
      xbacklight -set 30 -ctrl intel_backlight
      ;;

    battery-percentage-10|battery-percentage-8|battery-percentage-6)
      notify-send "Battery very low. System will hibernate automatically at 5%"
      ;;

    battery-percentage-5)
      notify-send "Hibernating in 5 seconds..."
      sleep 5 & wait
      sudo systemctl hibernate
      ;;
  esac
}

# Process every argument individually, in case this gets called with several
for arg in "$@"; do
  rules "$arg"
done
