#!/usr/bin/env bash
#
# Desktop Handler for xorg general settings
# This is called at the start of a X session to setup common or static configs, such as double-click
# delays, cursor shapes, etc.

# Disable automatic DPMS triggering -- use X11 ScreenSaver (XSS) instead
xset dpms 0 0 0 &

# Setup Screensaver XSS
#
# These two flags are simply to avoid X11 unecessaryly attempting to render/blanking screen when
# triggering the screen saver, as it should be handled by an external application.
xset s noexpose &
xset s noblank &

# This sets timeout to 0 (turning screen saver off at this point) and cycle to 5. The meaning of
# these values are that timeout is how much time after idling it will trigger the ScreenSaver ON,
# while the cycle is, after being on, how often it will trigger its cycle event, originally meant
# for changing background patterns to avoid burn-in, but in this case it's used to flag `xss-lock`
# that the locker can be called - otherwise, it would only call the notify program.
# See more on xss-lock(1) and on screen-locker.
#
# Recommendation: Keep the second parameter the amount of time that the dimmer needs to fade out
# completely before showing the locker - usually 5 seconds.
xset s 0 5 &

# Disable bell
xset b off &

# Configure cursor
xsetroot -cursor_name left_ptr &

# Configure monitor DPI globally
~/.bin/monitor-dpi 96 &

# Set some important environment variables
#
# GTK3 apps try to contact org.a11y.Bus. Disable that.
export NO_AT_BRIDGE=1

# Makes scrolling bars always visible on GTK apps
export GTK_OVERLAY_SCROLLING=0

# Make QT automatically scale according to screen DPI
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# Use GTK widgets on QT where applicable (such as on file picker)
export QT_QPA_PLATFORMTHEME=gtk3
export QT_STYLE_OVERRIDE=adwaita

# Add ~/.bin to PATH
export PATH="$HOME/.bin:/usr/local/bin:/usr/bin"

# And import them
systemctl --user import-environment \
  NO_AT_BRIDGE GTK_OVERLAY_SCROLLING QT_AUTO_SCREEN_SCALE_FACTOR QT_QPA_PLATFORMTHEME \
  QT_STYLE_OVERRIDE PATH

wait
