#!/usr/bin/env bash
#
# Apply xorg general settings
# This is called at the start of a X session to setup common or static configs, such as double-click
# delays, cursor shapes, etc.

# Set some important environment variables
#
# GTK3 apps try to contact org.a11y.Bus. Disable that.
export NO_AT_BRIDGE=1

# Makes scrolling bars always visible on GTK apps
export GTK_OVERLAY_SCROLLING=0

# Make QT automatically scale according to screen DPI
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough

# Use GTK widgets on QT where applicable (such as on file picker)
export QT_QPA_PLATFORMTHEME=gtk3
export QT_STYLE_OVERRIDE=adwaita

# Add ~/.bin to PATH
export PATH="$HOME/.bin:/usr/local/bin:/usr/bin"

# Then import them to user systemd instance
systemctl --user import-environment \
  NO_AT_BRIDGE GTK_OVERLAY_SCROLLING QT_AUTO_SCREEN_SCALE_FACTOR QT_SCALE_FACTOR_ROUNDING_POLICY \
  QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE PATH &

# Disable automatic DPMS triggering -- use X11 ScreenSaver (XSS) instead
xset dpms 0 0 0 &

# Setup Screensaver XSS
#
# These two flags are simply to avoid X11 unecessaryly attempting to render/blanking screen when
# triggering the screen saver, as it should be handled by an external application.
xset s noexpose &
xset s noblank &

# Disable bell
xset b off &

# Configure cursor
xsetroot -cursor_name left_ptr &

# Configure monitor DPI globally
monitor-dpi 96 &

wait
